import "~/styles/globals.css";
import { type Metadata } from "next";

// import { Geist } from "next/font/google"; // Mantido comentado
// import { TRPCReactProvider } from "~/trpc/react"; // TRPCProvider Removido temporariamente para isolar o erro

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// const geist = Geist({
//   subsets: ["latin"],
//   variable: "--font-geist-sans",
// }); // Mantido comentado

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // As tags <html> e <body> foram removidas. O Next.js App Router cuida disso.
  // A classe de fonte, se necessária, deve ser aplicada ao elemento body via CSS global ou de outra forma compatível.
  // TRPCProvider foi removido temporariamente.
  return (
    <>{children}</> // Envolvendo children em um fragmento simples
  );
}

